In [1]:
# importas la paquetería y le asignas un nombre para una interpretación más sencilla de las funciones de la misma
import numpy as np

# Numpy Arrays

In [2]:
# generar datos aleatorios
data = np.random.randn(2,3) # defines las dimensiones de la matriz
data

array([[-1.92016071, -1.61510223, -0.03679915],
       [-0.64436858,  1.14673008, -0.3035892 ]])

In [3]:
data * 5 # multiplicación de matrices

array([[-9.60080356, -8.07551113, -0.18399575],
       [-3.22184292,  5.73365042, -1.51794601]])

In [4]:
data + data # suma de matrices

array([[-3.84032143, -3.23020445, -0.0735983 ],
       [-1.28873717,  2.29346017, -0.6071784 ]])

In [5]:
data.shape # que dimensiones tiene la matriz

(2, 3)

In [6]:
data.dtype # tipo de datos de la matriz

dtype('float64')

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
# crear un vector de 0s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# crear una matriz de 0s
np.zeros((3, 6)) # necesitamos utilizar una tupla para poder realizar esto

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.empty((2, 3, 2)) # regresa valores basura o poco importantes

array([[[-1.28822975e-231, -1.28822975e-231],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  1.31289400e-071]],

       [[ 1.16188789e+165,  4.95625938e-090],
        [ 1.77136066e-051,  2.10716426e-076],
        [-1.28822975e-231,  8.38745136e-309]]])

In [14]:
np.arange(15) # nos regresa una secuencia, parecido a range() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Operaciones aritmeticas

In [15]:
arr = np.array([[1,2,3],[4,5,6]]) # definimos nuestro array inicial
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr * arr # multiplicación de matrices

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
arr - arr # resta de matrices

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
1 / arr # división de matrices

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [19]:
arr ** 0.5 # potencias

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [20]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [21]:
arr2 > arr # operaciones booleanas

array([[False,  True, False],
       [ True, False,  True]])

# Indexing y slicing

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5] # seleccionamos el valor en la posición 5

5

In [26]:
arr[5:8] # seleccionamos del valor en la posición 5 a la 8

array([5, 6, 7])

In [27]:
arr[5:8] = 12 # propagación de valores
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [28]:
arr_slice = arr[5:8] # seleccionamos ciertos valores
arr_slice

array([12, 12, 12])

In [30]:
arr_slice[1] = 12345 # definimos un valor en la selección anterior
arr # el valor termina por reflejarse en el vector original (no es una copia)

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [35]:
arr_slice[:] = 64 # podemos definir todos los valores de un array con :
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [34]:
arr_copia = arr.copy() # para crear una copia sin modificaciones en la original utilizamos el metodo copy()
arr_copia

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # definimos nuestra matriz de 2d
arr2d[2] # indexamos el elemento 2

array([7, 8, 9])

In [38]:
arr2d[0][2] # indexamos el elemento 2 del elemento 0

3

In [39]:
arr2d[0, 2] # # indexamos el elemento 2 del elemento 0

3

In [43]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # matriz de 3 dimensiones
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[0] # primer elemento de la matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[1, 0]

array([7, 8, 9])

In [48]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
x[0]

array([7, 8, 9])